-- Maquette pédagogique ISM Dakar — initialisation

-- 1. Classes de référence
INSERT INTO classes_ref (nom, niveau, filiere, actif) VALUES
  ('L1 GLRS',     'L1',       'GLRS',      true),
  ('L2 GLRS',     'L2',       'GLRS',      true),
  ('L3 GLRS',     'L3',       'GLRS',      true),
  ('L1 TC',       'L1',       'TC',        true),
  ('L3 GRH',      'L3',       'GRH',       true),
  ('L3 Finance',  'L3',       'Finance',   true),
  ('L3 Marketing','L3',       'Marketing', true),
  ('M1 GRH',      'MASTER_1', 'GRH',       true),
  ('M2 GRH',      'MASTER_2', 'GRH',       true),
  ('M1 Finance',  'MASTER_1', 'Finance',   true),
  ('M2 Finance',  'MASTER_2', 'Finance',   true),
  ('M1 Marketing','MASTER_1', 'Marketing', true),
  ('M2 Marketing','MASTER_2', 'Marketing', true)
ON CONFLICT (nom) DO NOTHING;

-- 2. Modules de référence
INSERT INTO modules_ref (nom, actif) VALUES
  ('Business English 1', true),
  ('Business English 2', true),
  ('Business English 3', true),
  ('Business English 4', true),
  ('Statistiques Descriptives', true),
  ('CISCO IT Essentials 1 : PC Hardware & Software', true),
  ('Algorithmique et Langages de Programmation', true),
  ('Technologies Web 1 : HTML5 - CSS3', true),
  ('Informatique Appliquée', true),
  ('Fondamentaux du Management', true),
  ('Droit du Numérique', true),
  ('Programmation Objet 1 : Python', true),
  ('Algorithmique et Structures de Données 1', true),
  ('CMS WordPress', true),
  ('Analyse Combinatoire et Lois de Probabilité', true),
  ('Architecture des Réseaux Informatiques : CISCO CCNA 1-2', true),
  ('Administration Système Windows', true),
  ('Programmation Objet 2 : Python', true),
  ('Programmation C', true),
  ('Programmation Web 1 : PHP', true),
  ('Analyse et Conception 1 (UML)', true),
  ('Systèmes de Gestion de Bases de Données', true),
  ('Administration Systèmes Linux', true),
  ('Programmation Objet 3 : Python', true),
  ('Programmation Objet 4 : C++', true),
  ('Programmation Objet 5 : JAVA', true),
  ('Analyse et Conception 2', true),
  ('Technologies Web 3 : PHP/MySQL', true),
  ('English For IT (E-FIT) 1', true),
  ('English For IT (E-FIT) 2', true),
  ('Programmation Objet 6 : JAVA', true),
  ('Programmation Web 2 : PHP Orienté Objet - Framework Symfony', true),
  ('Technologies .NET (C#)', true),
  ('Administration de Bases de Données sous SQL Server', true),
  ('Fondamentaux de la Sécurité Informatique', true),
  ('Management de Projets Informatiques', true),
  ('Administration de Réseaux sous Windows Server', true),
  ('Génie Logiciel - Ateliers et Projets Développement d''Applications', true),
  ('Administration de Bases de Données sous Oracle', true),
  ('Développement d''Applications Mobile Flutter', true),
  ('Applications Angular', true),
  ('Framework Python : Flask', true),
  ('Management des Organisations', true),
  ('Management Stratégique', true),
  ('Ressources Humaines', true),
  ('Droit du Travail', true),
  ('Recrutement et Talent', true),
  ('Formation et Développement RH', true),
  ('Relations Sociales', true),
  ('Conduite du Changement', true),
  ('Gestion de Projet', true),
  ('Audit et Contrôle de Gestion', true),
  ('Finance d''Entreprise', true),
  ('Comptabilité Analytique', true),
  ('Analyse Financière', true),
  ('Fiscalité', true),
  ('Mathématiques Financières', true),
  ('Contrôle de Gestion', true),
  ('Marketing Stratégique', true),
  ('Marketing Digital', true),
  ('Comportement du Consommateur', true),
  ('Commerce International', true),
  ('Gestion de la Qualité', true)
ON CONFLICT (nom) DO NOTHING;

-- 3. Maquette : association classe × module × volume horaire
INSERT INTO maquette_modules (classe_ref_id, module_ref_id, volume_horaire, actif)
SELECT c.id, m.id, v.vh, true
FROM (VALUES
  ('L1 GLRS', 'Business English 1', 30),
  ('L1 GLRS', 'Statistiques Descriptives', 30),
  ('L1 GLRS', 'CISCO IT Essentials 1 : PC Hardware & Software', 40),
  ('L1 GLRS', 'Algorithmique et Langages de Programmation', 40),
  ('L1 GLRS', 'Technologies Web 1 : HTML5 - CSS3', 30),
  ('L1 GLRS', 'Informatique Appliquée', 20),
  ('L1 GLRS', 'Fondamentaux du Management', 20),
  ('L1 GLRS', 'Droit du Numérique', 20),
  ('L1 GLRS', 'Business English 2', 30),
  ('L1 GLRS', 'Programmation Objet 1 : Python', 40),
  ('L1 GLRS', 'Algorithmique et Structures de Données 1', 30),
  ('L1 GLRS', 'CMS WordPress', 20),
  ('L2 GLRS', 'Business English 3', 30),
  ('L2 GLRS', 'Analyse Combinatoire et Lois de Probabilité', 30),
  ('L2 GLRS', 'Architecture des Réseaux Informatiques : CISCO CCNA 1-2', 40),
  ('L2 GLRS', 'Administration Système Windows', 30),
  ('L2 GLRS', 'Programmation Objet 2 : Python', 30),
  ('L2 GLRS', 'Programmation C', 30),
  ('L2 GLRS', 'Programmation Web 1 : PHP', 30),
  ('L2 GLRS', 'Analyse et Conception 1 (UML)', 30),
  ('L2 GLRS', 'Systèmes de Gestion de Bases de Données', 30),
  ('L2 GLRS', 'Business English 4', 30),
  ('L2 GLRS', 'Administration Systèmes Linux', 40),
  ('L2 GLRS', 'Programmation Objet 3 : Python', 30),
  ('L2 GLRS', 'Programmation Objet 4 : C++', 30),
  ('L2 GLRS', 'Programmation Objet 5 : JAVA', 30),
  ('L2 GLRS', 'Analyse et Conception 2', 30),
  ('L2 GLRS', 'Technologies Web 3 : PHP/MySQL', 30),
  ('L3 GLRS', 'English For IT (E-FIT) 1', 30),
  ('L3 GLRS', 'Programmation Objet 6 : JAVA', 30),
  ('L3 GLRS', 'Programmation Web 2 : PHP Orienté Objet - Framework Symfony', 40),
  ('L3 GLRS', 'Technologies .NET (C#)', 30),
  ('L3 GLRS', 'Administration de Bases de Données sous SQL Server', 30),
  ('L3 GLRS', 'Fondamentaux de la Sécurité Informatique', 30),
  ('L3 GLRS', 'Management de Projets Informatiques', 30),
  ('L3 GLRS', 'English For IT (E-FIT) 2', 30),
  ('L3 GLRS', 'Administration de Réseaux sous Windows Server', 40),
  ('L3 GLRS', 'Génie Logiciel - Ateliers et Projets Développement d''Applications', 40),
  ('L3 GLRS', 'Administration de Bases de Données sous Oracle', 30),
  ('L3 GLRS', 'Développement d''Applications Mobile Flutter', 30),
  ('L3 GLRS', 'Applications Angular', 30),
  ('L3 GLRS', 'Framework Python : Flask', 30),
  ('L1 TC', 'Business English 1', 30),
  ('L1 TC', 'Fondamentaux du Management', 30),
  ('L1 TC', 'Informatique Appliquée', 30),
  ('L1 TC', 'Statistiques Descriptives', 30),
  ('L1 TC', 'Droit du Numérique', 20),
  ('L1 TC', 'Algorithmique et Langages de Programmation', 30),
  ('M1 GRH', 'Management des Organisations', 40),
  ('M1 GRH', 'Management Stratégique', 40),
  ('M1 GRH', 'Ressources Humaines', 40),
  ('M1 GRH', 'Droit du Travail', 40),
  ('M1 GRH', 'Recrutement et Talent', 30),
  ('M1 GRH', 'Formation et Développement RH', 30),
  ('M1 GRH', 'Relations Sociales', 30),
  ('M1 GRH', 'Conduite du Changement', 30),
  ('M1 GRH', 'Gestion de Projet', 30),
  ('M2 GRH', 'Management Stratégique', 40),
  ('M2 GRH', 'Ressources Humaines', 40),
  ('M2 GRH', 'Droit du Travail', 40),
  ('M2 GRH', 'Relations Sociales', 30),
  ('M2 GRH', 'Conduite du Changement', 30),
  ('M2 GRH', 'Audit et Contrôle de Gestion', 30),
  ('M1 Finance', 'Finance d''Entreprise', 40),
  ('M1 Finance', 'Comptabilité Analytique', 40),
  ('M1 Finance', 'Audit et Contrôle de Gestion', 40),
  ('M1 Finance', 'Analyse Financière', 40),
  ('M1 Finance', 'Fiscalité', 40),
  ('M1 Finance', 'Mathématiques Financières', 30),
  ('M1 Finance', 'Contrôle de Gestion', 30),
  ('M2 Finance', 'Finance d''Entreprise', 40),
  ('M2 Finance', 'Audit et Contrôle de Gestion', 40),
  ('M2 Finance', 'Analyse Financière', 40),
  ('M2 Finance', 'Fiscalité', 40),
  ('M2 Finance', 'Contrôle de Gestion', 30),
  ('M1 Marketing', 'Marketing Stratégique', 40),
  ('M1 Marketing', 'Marketing Digital', 40),
  ('M1 Marketing', 'Comportement du Consommateur', 30),
  ('M1 Marketing', 'Gestion de Projet', 30),
  ('M2 Marketing', 'Marketing Stratégique', 40),
  ('M2 Marketing', 'Marketing Digital', 40),
  ('M2 Marketing', 'Commerce International', 30),
  ('L3 GRH', 'Ressources Humaines', 40),
  ('L3 GRH', 'Droit du Travail', 40),
  ('L3 GRH', 'Management des Organisations', 30),
  ('L3 GRH', 'Recrutement et Talent', 30),
  ('L3 GRH', 'Gestion de la Qualité', 30),
  ('L3 Finance', 'Finance d''Entreprise', 40),
  ('L3 Finance', 'Comptabilité Analytique', 40),
  ('L3 Finance', 'Audit et Contrôle de Gestion', 30),
  ('L3 Finance', 'Fiscalité', 30),
  ('L3 Finance', 'Analyse Financière', 30),
  ('L3 Marketing', 'Marketing Stratégique', 40),
  ('L3 Marketing', 'Marketing Digital', 40),
  ('L3 Marketing', 'Comportement du Consommateur', 30),
  ('L3 Marketing', 'Commerce International', 30)
) AS v(classe_nom, module_nom, vh)
JOIN classes_ref c ON c.nom = v.classe_nom
JOIN modules_ref m ON m.nom = v.module_nom
ON CONFLICT (classe_ref_id, module_ref_id) DO UPDATE SET volume_horaire = EXCLUDED.volume_horaire;
